## Bernoulli Matrix

In [29]:
import numpy as np

In [32]:
def bernoulli(m, n):

    A = np.random.choice( (0,1), (m, n) )
    return A

In [33]:
print bernoulli(3,5)

[[1 0 1 0 0]
 [1 1 1 1 0]
 [0 0 1 1 0]]


## Gaussian Matrix

In [34]:
def normalize(v):
    norm = np.linalg.norm(v)
    if norm==0:
        return v 
    else:
        return v/np.linalg.norm(v)
    

def column_normalize(A): 
    n       = A.shape[1]
    cols    = np.hsplit(A, n)
    return  np.hstack([ normalize(col) for col in cols ])